module(load="imtcp")

global(
    DefaultNetstreamDriver="gtls"
    DefaultNetstreamDriverCAFile="/etc/rsyslog/ssl/ca.crt"
    DefaultNetstreamDriverCertFile="/etc/rsyslog/ssl/server.crt"
    DefaultNetstreamDriverKeyFile="/etc/rsyslog/ssl/server.key"
)

input(
    type="imtcp"
    port="6514"
    StreamDriver.Name="gtls"
    StreamDriver.Mode="1"
    StreamDriver.AuthMode="x509/name"
    PermittedPeer="sec-workstation"
)
