global(
    DefaultNetstreamDriver="gtls"
    DefaultNetstreamDriverCAFile="/etc/rsyslog/ssl/ca.crt"
    DefaultNetstreamDriverCertFile="/etc/rsyslog/ssl/workstation.crt"
    DefaultNetstreamDriverKeyFile="/etc/rsyslog/ssl/workstation.key"
)

action(
    type="omfwd"
    target="192.168.223.135"
    port="6514"
    protocol="tcp"
    StreamDriver="gtls"
    StreamDriverMode="1"
    StreamDriverAuthMode="x509/name"
    StreamDriverPermittedPeers="sec-server"
    action.resumeRetryCount="-1"
    queue.type="linkedList"
    queue.filename="tls_forward"
    queue.saveOnShutdown="on"
)
